version: "3.4"
services:

  asterisk:
    image: alexshander/asterisk:13.37.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

  postgres:
    image: postgres:12.6-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-firs
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 1
        window: 120s
