version: "3.9"
services:

  asterisk:
    image: alexshander/asterisk:18.3-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    entrypoint: ["/usr/sbin/asterisk", "-fvvv"]
    volumes:
      - asterisk-spool:/var/spool/asterisk
      - asterisk-configure:/etc/asterisk
      - asterisk-sounds:/var/lib/asterisk/sounds
    networks:
      - swarm-asterisk
      - db-backend

  asterisk-db:
    image: postgres:13.3-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=asterisk
    volumes:
      - asterisk-db-data:/var/lib/postgresql/data
      - $PWD/../sql/asteriskcdrdb.sql:/docker-entrypoint-initdb.d/asteriskcdrdb.sql
    networks:
      - db-backend

  asterisk-grafana:
    image: grafana/grafana:7.5.6
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    networks:
      - db-backend

  asterisk-nginx:
    image: nginx:1.20.0-alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    volumes:
      - $PWD/../nginx/app.conf:/etc/nginx/conf.d/app.conf
      - $PWD/../nginx/dnsname.conf:/etc/nginx/confvars/dnsname.conf
      - asterisk-spool:/var/spool/asterisk
    networks:
      - db-backend


networks:
  swarm-asterisk:
    external: true
    driver: macvlan
  db-backend:
    external: false
    driver: overlay

volumes:
  asterisk-configure:
  asterisk-db-data:
  asterisk-spool:
  asterisk-sounds:
