version: "3.4"
services:

  asterisk:
    image: alexshander/asterisk:13.37.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

