version: "3.9"
services:

  asterisk:
    image: 6391725ysd/asterisk-18.3
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    networks:
      swarm-sip:

        
networks:
  swarm-sip:
    external: true
    driver: macvlan
